### ISSUE TITLE
升级2.5.0版本后出现大量崩溃错误

### ISSUE THREAD

**Issue by nnianhouss** [FlutterAds/flutter_qq_ads#21]
经过测试,升级2.5.0版本后出现大量崩溃错误,降级到之前的2x分支未出现如下错误

2.5.0的版本错误如图,相关日志已经贴出来

<img width="1204" alt="截屏2022-04-20 09 10 26" src="https://user-images.githubusercontent.com/10951126/164127087-5a5a3ba5-1f7e-4867-bc31-0f557812a08e.png">

Thread Name: 'main'
Back traces starts.
java.lang.NullPointerException: Attempt to write to field 'com.qq.e.ads.nativ.NativeExpressADView$ViewBindStatusListener com.qq.e.comm.plugin.gdtnativead.o.d' on a null object reference
	at com.qq.e.comm.plugin.gdtnativead.o.setViewBindStatusListener(A:1)
	at com.qq.e.comm.plugin.intersitial2.a$a.run(A:173)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8215)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1031)
Back traces ends.

//=========================================================

Thread Name: 'main'
Back traces starts.
java.lang.IllegalArgumentException: Unsupported value: '[Ljava.util.List;@39a9ba6' of type 'class [Ljava.util.List;'
	at f.a.c.a.q.p(Unknown Source:444)
	at f.a.c.a.r.c(Unknown Source:11)
	at f.a.c.a.j$a$a.a(Unknown Source:10)
	at com.zero.flutter_qq_ads.d.a.onNoAD(Unknown Source:68)
	at com.qq.e.ads.nativ.NativeExpressAD.d(Unknown Source:352)
	at com.qq.e.ads.nativ.NativeExpressAD$ADListenerAdapter.onADEvent(Unknown Source:16)
	at com.qq.e.comm.plugin.gdtnativead.h$d.run(A:1)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:230)
	at android.app.ActivityThread.main(ActivityThread.java:7880)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
Back traces ends.

//=========================================================
Thread Name: 'main'
Back traces starts.
java.lang.IncompatibleClassChangeError: Class 'com.qq.e.ads.banner2.ADListenerAdapter' does not implement interface 'com.qq.e.comm.pi.NEADVI' in call to 'void com.qq.e.comm.pi.NEADVI.render()' (declaration of 'com.qq.e.comm.plugin.gdtnativead.o' appears in gdt_plugin.jar)
	at com.qq.e.comm.plugin.gdtnativead.o.render(A:2)
	at com.qq.e.comm.plugin.banner2.a$a.run(A:70)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8073)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
Back traces ends.

//========================================================

Thread Name: 'main'
Back traces starts.
java.lang.NullPointerException: Attempt to invoke interface method 'void com.qq.e.comm.pi.NEADVI.setAdListener(com.qq.e.comm.adevent.ADListener)' on a null object reference
	at com.qq.e.comm.plugin.gdtnativead.o.a(A:17)
	at com.qq.e.comm.plugin.gdtnativead.o.a(A:3)
	at com.qq.e.comm.plugin.gdtnativead.o$a.run(A:3)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
Back traces ends.

**Comment by nnianhouss** [comment]
升级依赖后好像好了

**Comment by BytesZero** [comment]
好的
